/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/boardig30.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/boardig30.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.23, 2.891, 0.623]} scale={[0.091, 1, 1.318]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.base} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.inner} />
      </group>
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[-0.731, 1.761, 0.645]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.115, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/boardig30.glb')
